version: "3.9"

services:
  app:
    build:
      context: .
      args:
        FONTAWESOME_NPM_AUTH_TOKEN: "$FONTAWESOME_NPM_AUTH_TOKEN"
    image: ghcr.io/gabe565/patrol
    ports:
      - "80:80"
